---@class Type
---@field options Type[]
---@field value Type
---@field key Type
---@field parameters Type[]
---@field variant_parameter_groups ParameterGroup[]
---@field variant_parameter_description string