---@class ComplexType
---@field complex_type string
---@field options? Type[]
---@field value? Type
---@field key? Type
---@field parameters? (Parameter|Type)[]
---@field variant_parameter_groups? ParameterGroup[]
---@field variant_parameter_description? string
